# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\UI_MESS_TEST\MES.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 200)
        MainWindow.setMinimumSize(QtCore.QSize(350, 200))
        MainWindow.setMaximumSize(QtCore.QSize(350, 200))
        MainWindow.setStyleSheet("border: 1px solid #000;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 8, 111, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border-color: none; font-weight: bold; ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txtscan = QtWidgets.QTextEdit(self.groupBox)
        self.txtscan.setGeometry(QtCore.QRect(10, 50, 144, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txtscan.setFont(font)
        self.txtscan.setStyleSheet("border-color: #fff; background-color: #fff; border-radius: 4px;\n"
"")
        self.txtscan.setObjectName("txtscan")
        self.reset_btn = QtWidgets.QPushButton(self.groupBox)
        self.reset_btn.setGeometry(QtCore.QRect(10, 150, 143, 23))
        self.reset_btn.setStyleSheet("background-color: rgb(194, 194, 194)")
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(23, 10, 109, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-color: none; font-weight: bold; ")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ruleresult = QtWidgets.QTextEdit(self.groupBox_2)
        self.ruleresult.setGeometry(QtCore.QRect(10, 50, 144, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.ruleresult.setFont(font)
        self.ruleresult.setStyleSheet("border-color: #fff; background-color: #fff; border-radius: 4px;\n"
"")
        self.ruleresult.setObjectName("ruleresult")
        self.lblMoveOUTQTY = QtWidgets.QLineEdit(self.groupBox_2)
        self.lblMoveOUTQTY.setGeometry(QtCore.QRect(10, 151, 143, 21))
        self.lblMoveOUTQTY.setObjectName("lblMoveOUTQTY")
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HO-51    ver:1.0.0.47     Login:V3092552"))
        self.label.setText(_translate("MainWindow", "SCAN DATA"))
        self.txtscan.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.reset_btn.setText(_translate("MainWindow", "RESET"))
        self.label_2.setText(_translate("MainWindow", "RESULT"))
